// <auto-generated />
namespace Gcc.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenomeadoClasseParticipanteGrupo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenomeadoClasseParticipanteGrupo));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101734141_RenomeadoClasseParticipanteGrupo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
