// <auto-generated />
namespace Gcc.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdicionadoEnqueteNoVoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionadoEnqueteNoVoto));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101728101_AdicionadoEnqueteNoVoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
