// <auto-generated />
namespace Gcc.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlteracaoCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaoCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091745438_AlteracaoCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
