//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Caracteristica
    {
        public long CaracteristicaID { get; set; }
        public Nullable<long> ProdutoID { get; set; }

        [Required(ErrorMessage = "Nome da Característica é um campo de preenchimento obrigatório.")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Valor da Característica é um campo de preenchimento obrigatório.")]
        public string Valor { get; set; }

        [Required(ErrorMessage = "Unidade de Medida da Característica é um campo de preenchimento obrigatório.")]
        public string UnidadeMedida { get; set; }

        public virtual Produto Produto { get; set; }
    }
}
