//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Caracteristica
    {
        public long CaracteristicaID { get; set; }
        public Nullable<long> ProdutoID { get; set; }        
        public string Nome { get; set; }        
        public string Valor { get; set; }       
        public string UnidadeMedida { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
