//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ParticipantesGrupoes = new HashSet<ParticipantesGrupo>();
            this.ProdutoRequeridoes = new HashSet<ProdutoRequerido>();
            this.Votoes = new HashSet<Voto>();
        }
    
        public long ClienteID { get; set; }
        public Nullable<long> EnderecoID { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Nome { get; set; }
        public DateTime? Idade { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual ICollection<ParticipantesGrupo> ParticipantesGrupoes { get; set; }
        public virtual ICollection<ProdutoRequerido> ProdutoRequeridoes { get; set; }
        public virtual ICollection<Voto> Votoes { get; set; }
    }
}
