//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Enquetes = new HashSet<Enquete>();
            this.ParticipantesGrupoes = new HashSet<ParticipantesGrupo>();
            this.Produtoes = new HashSet<Produto>();
            this.ProdutoRequeridoes = new HashSet<ProdutoRequerido>();
        }
    
        public long GrupoID { get; set; }
        public Nullable<long> EnderecoID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> QuantidadeTotal { get; set; }
        public string Visibilidade { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual ICollection<Enquete> Enquetes { get; set; }
        public virtual ICollection<ParticipantesGrupo> ParticipantesGrupoes { get; set; }
        public virtual ICollection<Produto> Produtoes { get; set; }
        public virtual ICollection<ProdutoRequerido> ProdutoRequeridoes { get; set; }
    }
}
