//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipanteGrupo
    {
        public long ParticipanteGrupoID { get; set; }
        public Nullable<long> GrupoID { get; set; }
        public Nullable<long> ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
