//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Produto
    {
        public Produto()
        {
            this.Caracteristicas = new HashSet<Caracteristica>();
            this.ProdutoRequeridoes = new HashSet<ProdutoRequerido>();
        }

        public long ProdutoID { get; set; }
        public Nullable<long> GrupoID { get; set; }
        [Required(ErrorMessage = "Nome do Produto é um campo de preenchimento obrigatório.")]
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Link { get; set; }
        [Required(ErrorMessage = "Unidade de Medida é um campo de preenchimento obrigatório.")]
        public string UnidadeMedida { get; set; }

        public virtual ICollection<Caracteristica> Caracteristicas { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<ProdutoRequerido> ProdutoRequeridoes { get; set; }
    }
}
