//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public long VotoID { get; set; }
        public Nullable<long> ClienteID { get; set; }
        public Nullable<long> AlternativaID { get; set; }
        public Nullable<long> EnqueteID { get; set; }
    
        public virtual Alternativa Alternativa { get; set; }
        public virtual Enquete Enquete { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
